/**
 * @file DynamicProductName.tsx
 * @layer Component
 * @feature catalog
 * @description UI component cho feature catalog
 */
import React, { useState, useEffect, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { Form, Alert, Skeleton, Tag, Space, Typography, Divider } from 'antd';
import { BulbOutlined, SyncOutlined, CheckCircleOutlined } from '@ant-design/icons';
import { useDebounce } from '@/hooks/use-debounce';
import { attributeService } from '../api/attribute-api';

const { Text, Title } = Typography;

interface DynamicProductNameProps {
  baseName?: string;
  selectedAttributes?: Record<string, string>;
  productId?: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- AI response details
  onNameGenerated?: (name: string, details: any) => void;
  disabled?: boolean;
}

interface NamePreview {
  originalName: string;
  generatedName: string;
  hasChanges: boolean;
  parts: string[];
  affectingAttributes?: Array<{
    id: string;
    name: string;
    nameTemplate: string;
    groupName: string;
    groupType: string;
  }>;
  suggestions?: string[];
}

const DynamicProductName: React.FC<DynamicProductNameProps> = ({
  baseName,
  selectedAttributes = {},
  productId,
  onNameGenerated,
  disabled = false,
}) => {
  const { t } = useTranslation();
  const form = Form.useFormInstance();
  const [loading, setLoading] = useState(false);
  const [namePreview, setNamePreview] = useState<NamePreview | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Debounce input để tránh gọi API quá nhiều
  const debouncedBaseName = useDebounce(baseName, 300);
  const debouncedAttributes = useDebounce(selectedAttributes, 500);

  // Tạo tên khi input thay đổi
  const shouldGenerateName = useMemo(() => {
    return (
      debouncedBaseName && Object.values(debouncedAttributes).some((value) => value) && !disabled
    );
  }, [debouncedBaseName, debouncedAttributes, disabled]);

  const generateName = async () => {
    if (!shouldGenerateName) {
      setNamePreview(null);
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const response = await attributeService.generateNameRealTime({
        baseName: debouncedBaseName || '',
        attributeValues: debouncedAttributes,
        productId,
      });

      if (response.status === 'success' && response.data) {
        setNamePreview(response.data);

        // Thông báo cho component cha
        if (onNameGenerated) {
          onNameGenerated(response.data.generatedName, response.data);
        }

        // Tự động cập nhật trường form nếu khác giá trị hiện tại
        const currentName = form.getFieldValue('name');
        if (currentName !== response.data.generatedName) {
          form.setFieldValue('name', response.data.generatedName);
        }
      }
    } catch (err) {
      console.error('Lỗi tạo tên:', err);
      setError(err instanceof Error ? err.message : 'Failed to generate product name');
    } finally {
      setLoading(false);
    }
  };

  // Effect tạo tên khi input thay đổi
  useEffect(() => {
    generateName();
    // eslint-disable-next-line react-hooks/exhaustive-deps -- generateName dùng shouldGenerateName bên trong, deps đã đủ qua useMemo
  }, [shouldGenerateName]);

  // Đặt lại khi disabled
  useEffect(() => {
    if (disabled) {
      setNamePreview(null);
      setError(null);
    }
  }, [disabled]);

  if (!baseName && !disabled) {
    return (
      <Alert
        message={t('product.baseNameRequired')}
        description={t('product.baseNameRequiredDesc')}
        type="info"
        icon={<BulbOutlined />}
        style={{ marginBottom: 16 }}
      />
    );
  }

  if (disabled) {
    return null;
  }

  return (
    <div style={{ marginBottom: 24 }}>
      {/* Generated Name Preview */}
      {loading ? (
        <div
          style={{
            padding: '12px 16px',
            background: '#f5f5f5',
            borderRadius: 6,
            marginBottom: 16,
          }}
        >
          <Space>
            <SyncOutlined spin />
            <Text>{t('product.generatingName')}</Text>
          </Space>
          <Skeleton.Input style={{ width: 300, marginLeft: 16 }} active size="small" />
        </div>
      ) : namePreview ? (
        <div style={{ marginBottom: 16 }}>
          <div
            style={{
              padding: '16px',
              background: namePreview.hasChanges ? '#f6ffed' : '#f5f5f5',
              borderRadius: 8,
              border: namePreview.hasChanges ? '1px solid #b7eb8f' : '1px solid #d9d9d9',
            }}
          >
            <Space size="small" style={{ marginBottom: 8 }}>
              <CheckCircleOutlined style={{ color: '#52c41a' }} />
              <Text strong>{t('product.autoGeneratedLabel')}</Text>
            </Space>

            <Title level={5} style={{ margin: 0, color: '#1890ff' }}>
              {namePreview.generatedName}
            </Title>

            {namePreview.hasChanges && (
              <div style={{ marginTop: 8 }}>
                <Text type="secondary" style={{ fontSize: 12 }}>
                  {t('product.originalNameFull', { name: namePreview.originalName })}
                </Text>
              </div>
            )}
          </div>

          {/* Name Parts Breakdown */}
          {namePreview.parts.length > 1 && (
            <div style={{ marginTop: 12 }}>
              <Text type="secondary" style={{ fontSize: 12, marginBottom: 8, display: 'block' }}>
                {t('product.nameParts')}
              </Text>
              <Space wrap size="small">
                {namePreview.parts.map((part, index) => (
                  <Tag key={index} color={index === 0 ? 'blue' : 'green'} style={{ fontSize: 11 }}>
                    {part}
                  </Tag>
                ))}
              </Space>
            </div>
          )}

          {/* Affecting Attributes */}
          {namePreview.affectingAttributes && namePreview.affectingAttributes.length > 0 && (
            <div style={{ marginTop: 12 }}>
              <Text type="secondary" style={{ fontSize: 12, marginBottom: 8, display: 'block' }}>
                {t('product.affectingAttrs')}
              </Text>
              <Space wrap size="small">
                {namePreview.affectingAttributes.map((attr) => (
                  <Tag
                    key={attr.id}
                    color="orange"
                    style={{ fontSize: 11 }}
                    title={`${attr.groupName}: ${attr.name}`}
                  >
                    {attr.nameTemplate || attr.name}
                  </Tag>
                ))}
              </Space>
            </div>
          )}
        </div>
      ) : null}

      {/* Error State */}
      {error && (
        <Alert
          message={t('product.nameGenError')}
          description={error}
          type="error"
          closable
          onClose={() => setError(null)}
          style={{ marginBottom: 16 }}
        />
      )}

      {/* Suggestions (if available) */}
      {namePreview?.suggestions && namePreview.suggestions.length > 0 && (
        <div>
          <Divider style={{ margin: '12px 0' }} />
          <Text type="secondary" style={{ fontSize: 12, marginBottom: 8, display: 'block' }}>
            {t('product.variantSuggestions')}
          </Text>
          <Space wrap size="small">
            {namePreview.suggestions.slice(0, 3).map((suggestion, index) => (
              <Tag
                key={index}
                style={{ fontSize: 11, cursor: 'pointer' }}
                onClick={() => {
                  // Có thể triển khai click để áp dụng gợi ý
                }}
              >
                {suggestion}
              </Tag>
            ))}
          </Space>
        </div>
      )}

      {/* Helper Text */}
      {!Object.values(selectedAttributes).some((v) => v) && baseName && (
        <Alert
          message={t('product.selectAttrForName')}
          description={t('product.baseAttrNameDesc')}
          type="info"
          icon={<BulbOutlined />}
          style={{ marginTop: 16 }}
        />
      )}
    </div>
  );
};

export default DynamicProductName;
